Repository SSAFY-10th/algorithm, pull requests merged in 2023-07, with the labels that each got.

#2 [python] boj1260
  minjae9610/boj1260/README.md
  minjae9610/boj1260/boj1260.py
Labels: 알고리즘, #BFS/DFS

#7 [docs] organization 신규가입으로 인한 readme.md 수정
  README.md
Labels: DOCS

#9 [docs] 프로필 추가
  README.md
Labels: DOCS

#5 [java] boj15683
  zini9188/boj15683/README.md
  zini9188/boj15683/boj15683.java
Labels: 알고리즘, 브루트포스, 시뮬레이션

#3 [python] boj20529
  chjcoder/boj20529/README.md
  chjcoder/boj20529/boj20529.py
Labels: 알고리즘

#10 [cpp] boj14426.cpp
  cjh970422/boj14426/boj14426.cpp
Labels: 알고리즘, 백준

#14 [cpp] swea1974
  minjae9610/SWEA/D2/swea1974/README.md
  minjae9610/SWEA/D2/swea1974/swea1974.cpp
Labels: 알고리즘, #DP, SW Expert Academy

#20 [java] boj 6884
  lion0077v/BoJ/Silver II/Baekjoon_6884.java
  lion0077v/BoJ/Silver II/README.md
Labels: 알고리즘, 백준

#15 [python] swea7465.py
  서울_17_최준호/BOJ/boj14426.cpp
  서울_17_최준호/SWEA/swea7465.py
Labels: 알고리즘, #BFS/DFS, SW Expert Academy

#23 [java] boj 1986
  lion0077v/BoJ/Silver I/BoJ 1986/Baekjoon_1986.java
  lion0077v/BoJ/Silver I/BoJ 1986/README.md
Labels: 백준, #구현

#17 [cpp] swea1961
  minjae9610/SWEA/D2/swea1961/README.md
  minjae9610/SWEA/D2/swea1961/swea1961.cpp
Labels: 알고리즘, SW Expert Academy, #배열

#19 [cpp] swea1204
  minjae9610/SWEA/D2/swea1204/README.md
  minjae9610/SWEA/D2/swea1204/swea1204.cpp
Labels: 알고리즘, #DP, SW Expert Academy

#21 [java] boj 9465
  lion0077v/BoJ/Silver I/BoJ 9465/Baekjoon_9465.java
  lion0077v/BoJ/Silver I/BoJ 9465/README.md
  lion0077v/BoJ/Silver II/BoJ 6884/Baekjoon_6884.java
  lion0077v/BoJ/Silver II/BoJ 6884/README.md
Labels: 알고리즘, #DP, 백준

#26 [docs] readme 프로필 추가
  README.md
Labels: DOCS

#13 [docs] 프로필 추가
  README.md
Labels: DOCS

#16 [java] boj 11140
  lion0077v/BoJ/Silver III/boj11140/Baekjoon_11140.java
  lion0077v/BoJ/Silver III/boj11140/README.md
Labels: 알고리즘, 백준, #문자열

#27 [docs] KIMSEI1124 프로필 추가
  README.md
Labels: DOCS

#24 [java] boj 1138
  lion0077v/BoJ/Silver II/BoJ 1138/Baekjoon_1138.java
  lion0077v/BoJ/Silver II/BoJ 1138/README.md
Labels: 백준, #구현

#33 [cpp] 민코딩 DAT의 탑 12번 - 세 수의 합
  seoul_21_minjaekim/MinCoding/Algorithm Tower/DAT Tower/12/README.md
  seoul_21_minjaekim/MinCoding/Algorithm Tower/DAT Tower/12/min_dat_tower_12.cpp
Labels: #배열, 민코딩, #DAT

#35 [cpp] 민코딩 Backtracking의 탑 9번 - 좋은수열
  seoul_21_minjaekim/MinCoding/Algorithm Tower/Backtracking Tower/9/README.md
  seoul_21_minjaekim/MinCoding/Algorithm Tower/Backtracking Tower/9/min_backtracking_tower_9.cpp
Labels: 백준, 민코딩, #재귀, #BackTracking

#28 [docs] Add Sumin-Kim-dev profile
  README.md
Labels: DOCS

#32 [Java] 백준 11478
  seoul_18_kimjeonguk/BOJ/SILVER III/11478 - 서로 다른 부분 문자열의 개수/Q11478.java
  seoul_18_kimjeonguk/BOJ/SILVER III/11478 - 서로 다른 부분 문자열의 개수/readme.md
Labels: 백준, #문자열, #자료구조

#30 [DOCS] Update README.md
  README.md
Labels: DOCS

#34 [cpp] 민코딩 Backtracking의 탑 8번 - 다빈치 타워
  seoul_21_minjaekim/MinCoding/Algorithm Tower/Backtracking Tower/8/README.md
  seoul_21_minjaekim/MinCoding/Algorithm Tower/Backtracking Tower/8/min_backtracking_tower_8.cpp
Labels: 민코딩, #재귀, #BackTracking

#38 [cpp] 백준 2098 외판원 순회 - Gold I (민코딩 해밀턴 회로)
  seoul_21_minjaekim/BoJ/Gold I/boj2098/README.md
  seoul_21_minjaekim/BoJ/Gold I/boj2098/boj2098.cpp
Labels: #DFS, #DP, 백준, 민코딩, #재귀

#29 [java] boj 13335
  seoul_11_hongyungi/BoJ/Silver I/BoJ 13335/Baekjoon_13335.java
  seoul_11_hongyungi/BoJ/Silver I/BoJ 13335/README.md
  seoul_11_hongyungi/BoJ/Silver I/BoJ 1986/Baekjoon_1986.java
  seoul_11_hongyungi/BoJ/Silver I/BoJ 1986/README.md
  seoul_11_hongyungi/BoJ/Silver I/BoJ 9465/Baekjoon_9465.java
  seoul_11_hongyungi/BoJ/Silver I/BoJ 9465/README.md
  seoul_11_hongyungi/BoJ/Silver II/BoJ 6884/Baekjoon_6884.java
  seoul_11_hongyungi/BoJ/Silver II/BoJ 6884/README.md
  seoul_11_hongyungi/BoJ/Silver III/boj11140/Baekjoon_11140.java
  seoul_11_hongyungi/BoJ/Silver III/boj11140/README.md
Labels: #시뮬레이션, 백준, #구현, #자료구조
