Repository SSAFY-10th/algorithm, pull requests merged in 2023-08, with the labels that each got.

#36 [cpp] 민코딩 구현의 탑 5번 - 오목
  seoul_21_minjaekim/MinCoding/Algorithm Tower/Implement Tower/5/README.md
  seoul_21_minjaekim/MinCoding/Algorithm Tower/Implement Tower/5/min_implement_tower_5.cpp
Labels: #브루트포스, 백준, #구현, 민코딩, #DAT

#39 [docs] add kgh2120 profile
  README.md
Labels: DOCS

#50 [java] boj 15591
  seoul_11_hongyungi/BoJ/Gold V/Boj 15591/Boj15591.java
  seoul_11_hongyungi/BoJ/Gold V/Boj 15591/README.md
  seoul_11_hongyungi/BoJ/Silver II/BoJ 1138/Baekjoon_1138.java
  seoul_11_hongyungi/BoJ/Silver II/BoJ 1138/README.md
Labels: 백준, #BFS

#42 [JAVA] BOJ 21736 - 헌내기는 친구가 필요해
  seoul_09_kyoohyunkim/BOJ/Silver II/Boj 21736/Baekjoon_21736.java
  seoul_09_kyoohyunkim/BOJ/Silver II/Boj 21736/README.md
Labels: 백준, #BFS

#43 [cpp] 백준 2602 돌다리 건너기 - Gold IV (민코딩 돌다리 건너기)
  seoul_21_minjaekim/BoJ/Gold IV/boj2602/README.md
  seoul_21_minjaekim/BoJ/Gold IV/boj2602/boj2602.cpp
Labels: #DFS, #DP, 백준, 민코딩

#51 [cpp] 백준 2014 소수의 곱 - Gold I (민코딩 Ugly Number)
  seoul_21_minjaekim/BoJ/Gold I/boj2014/README.md
  seoul_21_minjaekim/BoJ/Gold I/boj2014/boj2014.cpp
Labels: 알고리즘, 백준, 민코딩, #PriorityQueue, #수학

#31 [cpp] mincodding DAT 12
  seoul_21_jongilchoi/mincodding/dat_12/README.md
  seoul_21_jongilchoi/mincodding/dat_12/dat_12.cpp
Labels: 민코딩, #DAT

#53 [cpp] Dijkstra의 탑 6번 - 무서운 시어머니
  seoul_21_minjaekim/MinCoding/Algorithm Tower/Dijkstra Tower/6/README.md
  seoul_21_minjaekim/MinCoding/Algorithm Tower/Dijkstra Tower/6/min_dijkstra_tower_6.cpp
Labels: 민코딩, #PriorityQueue, #Dijkstra

#54 [JAVA] 백준 10986 - 나머지 합 - Gold 3
  seoul_09_kyoohyunkim/BOJ/Gold III/boj 10986/Boj_10986.java
  seoul_09_kyoohyunkim/BOJ/Gold III/boj 10986/README.md
Labels: 백준, #수학

#59 [cpp] minco_bfs_13 solve
  seoul_21_jongilchoi/mincodding/bfs/13/README.md
  seoul_21_jongilchoi/mincodding/bfs/13/bfs_top_13.cpp
Labels: 민코딩, #BFS

#61 [java]boj 1167
  seoul_11_hongyungi/BoJ/Gold II/Boj 1167/Boj1167.java
  seoul_11_hongyungi/BoJ/Gold II/Boj 1167/ExampleTree.png
  seoul_11_hongyungi/BoJ/Gold II/Boj 1167/README.md
  seoul_11_hongyungi/BoJ/Platinum V/Boj 3015/Baekjoon_3015.java
  seoul_11_hongyungi/BoJ/Platinum V/Boj 3015/README.md
Labels: #DFS, 백준, #Tree
